### ISSUE TITLE
Problem with closing the game

### ISSUE THREAD

**Issue by KamiLordus** [libretro/scummvm#30]
I've noticed that CD versions of the Goblins 1, 2, and 3 series have a problem when trying to exit via F1 (retroarch menu) and then close game.
The "close content" option doesn't close the game, it just crashes retroarch.
The problem occurs on Goblins CD versions 1-3. floppy versions work fine. Other tested games also work fine.

**Comment by KamiLordus** [comment]
In this case, I am not able to say which update broke the game's closing function.
From what I can see, it must have been recently with one of the "fix core reset feature"
Because about a week ago games would close without a problem.
https://git.libretro.com/libretro/scummvm/-/pipelines?page=2&scope=all
Unfortunately none of the previous versions are available for download.

**Comment by KamiLordus** [comment]
I found another game with the same problem
Secret of Monkey Island (CD dos) (game ID: monkey)
Floppy version it closes without a problem.

**Comment by spleen1981** [comment]
fixed by 9a861391c861a1d4103df4e28444a375e885da72

**Comment by KamiLordus** [comment]
Fixed. Thank you very much.

**Comment by KamiLordus** [comment]
@spleen1981 One more thing, it's not a big deal but could you improve the closing of Beneath a Steel Sky?
Both cd and floppy close with a significant delay.
In the version 36e8aa19 that I checked, the closing of this game is ultra smooth.

Edit:
Ehhh Beneath a Steel Sky continues to close slowly :)
I thought I was able to fix it, but I just had an older version of the core. Sorry for the confusion.

**Comment by KamiLordus** [comment]
Fixed.
My mistake. The floppy/CD version had the game ID reversed in the retroarch list in the .scummvm files
Floppy - sky-1
CD - sky

**Comment by spleen1981** [comment]
can't reproduce this, but should be fixed by ce2e2f353d2a9f115d00be5b8177e580f3f378ff

**Comment by KamiLordus** [comment]
Unfortunately, it's still the same with Beneath. Only this game closes significantly longer and I tested 60 in my collection :)
In the latest update, there was another problem with scrolling the list of games in retroarch. When you close a game (Gobliins for example) the list doesn't stop at that game, it scrolls all the way to the top.

**Comment by spleen1981** [comment]
what's the exact core version you are currently testing?

> In the latest update, there was another problem with scrolling the list of games in retroarch.

That should not depend on the core, which cannot do any action in the frontend other than closing itself.

**Comment by KamiLordus** [comment]
This 41606901(master) - liberto build windows 64 archive.
The previous version 2fd912be does not have a list scrolling bug.

**Comment by spleen1981** [comment]
- can you check with 2fd912be5964758d7ed3e77a55bf3a3be695a39d if quitting from ScummVM GUI you see this "list scrolling bug"? At that commit the core was not closing content properly from quick menu, and I suspect the frontend was stuck to the last item launched, while the behaviour having now is retroarch intended one.
- can you provide a retroarch debug log for this delay with closing BASS from quick menu at 41606901e307af8c3345277afd281a4830996854? with my copies there is no delay.

**Comment by KamiLordus** [comment]
I went back to version 2fd912b and there is no problem with scrolling the list.
[retroarch.log](https://github.com/libretro/scummvm/files/11305229/retroarch.log)

**Comment by spleen1981** [comment]
ok, it seems we found an undocumented way to go to the top of the frontend playlist :) should be fixed with 5873ee968885676902df2c6765f0f520680ba80e, pls check if there is any regression regarding this thread and if it has any effect on BASS issue.
is the log above just launch the game/close content once? can you set the log level to DEBUG?

**Comment by KamiLordus** [comment]
[retroarch.log](https://github.com/libretro/scummvm/files/11308546/retroarch.log)
with frontend and core settings lvl 0 (debug)

with version 5873ee9 the list works fine again.
BASS works the same way, it turns off with a slight delay, about 3 seconds. I also tried deleting all scummvm files (including the .ini file and the entire playlist) and downloading everything again. However, it works the same. This is not a significant problem, but I wonder why only BASS turns off longer :)

edit:
@spleen1981 I have two questions regarding the RA core upgrade:
1. When launching a game from an RA playlist, the Scummvm logo sometimes appears, but this is completely random. Is there a way to add an option to permanently disable or enable this logo? (I prefer the first option).
![Bez tytułu](https://user-images.githubusercontent.com/123302593/234008043-2296275c-57c9-4ad8-a02a-8256f0f23ce1.png)

2. The scummvm on-screen keyboard has minor graphical errors (pink pixels). This is probably due to the file system/scummvm/extra/vkeybd_default.zip is surrounded by a pink frame. Can it be fixed?
![2](https://user-images.githubusercontent.com/123302593/234008129-fc883673-7fe5-4cda-b8c7-dc15112a9b8a.png)
![444](https://user-images.githubusercontent.com/123302593/234008399-26b15f53-5259-46f2-ac72-707bc78f9209.png)

It's just a question and very minor bugs. please don't hate me :)

**Comment by spleen1981** [comment]
> BASS works the same way, it turns off with a slight delay

compared to 36e8aa196f9b3c64caaec29d4d6b055dcfbd11c0 reported to quit quickly, now the core unloading makes sure scummvm thread is closed properly, while before it was just quitting.
I think BASS "delay" is due to the quit message "game over player one BE VIGILANT" which we don't see as we are alreading out of the video update loop at that point (but that you can see if you exit to the ScummVM GUI from within the game [ENTER] -> return to launcher).
So nothing to be done here, we have to live with those 3 secs delay.

>  Is there a way to add an option to permanently disable or enable this logo?

No, afaik.

> The scummvm on-screen keyboard has minor graphical errors (pink pixels)

That is part of "upstream" [scummvm source](https://github.com/scummvm/scummvm/tree/master/backends/vkeybd/packs), not specific to the core, so any issue can be submitted through the main [bug tracker](https://bugs.scummvm.org/)

**Comment by KamiLordus** [comment]
Thank you for the useful information.
