### ISSUE TITLE
Build error with gcc-15.1 on ARMv7

### ISSUE THREAD

**Issue by heitbaum** [libretro/scummvm#81]
With gcc-15.1 targeting ARMv7 build fails on lines like

https://github.com/libretro/scummvm/blob/9d31b31c179fd4a43f7cfc383a3435a9070c6aa8/engines/scumm/imuse/instrument.cpp#L432

s.syncAsSint32LE
s.syncAsByte

commenting out these lines allows the compiler to to proceed - so something to do with the s.sync<> …

Build Log of the error

```
during RTL pass: late_combine
/var/media/DATA/home-rudi/LibreELEC.kernel11/build.LibreELEC-H3.arm-13.0-devel/build/libretro-scummvm-9d31b31c179fd4a43f7cfc383a3435a9070c6aa8/backends/platform/libretro/../../../engines/scumm/imuse/instrument.cpp: In member function 'virtual void Scumm::Instrument_AdLib::saveLoadWithSerializer(Common::Serializer&)':
/var/media/DATA/home-rudi/LibreELEC.kernel11/build.LibreELEC-H3.arm-13.0-devel/build/libretro-scummvm-9d31b31c179fd4a43f7cfc383a3435a9070c6aa8/backends/platform/libretro/../../../engines/scumm/imuse/instrument.cpp:433:1: internal compiler error: Segmentation fault
  433 | }
      | ^
0x1dd2c77 diagnostic_context::diagnostic_impl(rich_location*, diagnostic_metadata const*, diagnostic_option_id, char const*, __va_list_tag (*) [1], diagnostic_t)
        ???:0
0x1de3bee internal_error(char const*, ...)
        ???:0
0xf36df3 crash_signal(int)
        ???:0
0x1cf0778 rtl_ssa::clobber_info::recompute_group()
        ???:0
0x1ca6947 rtl_ssa::access_info* rtl_ssa::last_access<(anonymous namespace)::insn_combination::substitute_nondebug_use(rtl_ssa::use_info*)::local_ignore>(rtl_ssa::def_info*, rtl_ssa::ignore_clobbers, (anonymous namespace)::insn_combination::substitute_nondebug_use(rtl_ssa::use_info*)::local_ignore)
        ???:0
0x1ca7ceb (anonymous namespace)::insn_combination::substitute_nondebug_uses(rtl_ssa::set_info*)
        ???:0
0x1ca79cb (anonymous namespace)::insn_combination::substitute_nondebug_uses(rtl_ssa::set_info*)
        ???:0
0x1ca8d6e (anonymous namespace)::late_combine::combine_into_uses(rtl_ssa::insn_info*, rtl_ssa::insn_info*)
        ???:0
0x1ca95d9 (anonymous namespace)::pass_late_combine::execute(function*)
        ???:0
Please submit a full bug report, with preprocessed source (by using -freport-bug).
Please include the complete backtrace with any bug report.
See <https://gcc.gnu.org/bugs/> for instructions.
make: *** [Makefile:676: engines/scumm/imuse/instrument.o] Error 1
make: *** Waiting for unfinished jobs....
FAILURE: s/build libretro-scummvm during make_target (default)
*********** FAILED COMMAND ***********
make ${PKG_MAKE_OPTS_TARGET}
**************************************
```

**Comment by spleen1981** [comment]
Not sure if it is a GCC bug or an optimization issue, can you try to reduce the optimization? It should be `-O3` by default, you may try `-O2`, `-O1` and `-O0` in order patching [here](https://github.com/libretro/scummvm/blob/2abffb36f4ee7091a446b2bf395ae672eef87610/backends/platform/libretro/Makefile#L551-L559).

**Comment by heitbaum** [comment]
👍 By changing the optimizer from O3 to O1 the compile completes. Below is the log from the failed O2 before it quits.

O1 success

```diff
--- a/backends/platform/libretro/Makefile  2025-05-21 22:58:59.591869661 +0000
+++ b/backends/platform/libretro/Makefile  2025-05-21 22:59:13.141125531 +0000
@@ -554,7 +554,7 @@
 else ifneq (,$(findstring $(platform), msvc genode rpi))
    DEFINES += -O2
 else
-   DEFINES += -O3
+   DEFINES += -O1
 endif
 
 ifeq ($(TARGET_64BIT), 1)
``` 

O2 failure

```diff
--- a/backends/platform/libretro/Makefile  2025-05-21 22:58:59.591869661 +0000
+++ b/backends/platform/libretro/Makefile  2025-05-21 22:59:13.141125531 +0000
@@ -554,7 +554,7 @@
 else ifneq (,$(findstring $(platform), msvc genode rpi))
    DEFINES += -O2
 else
-   DEFINES += -O3
+   DEFINES += -O2
 endif
 
 ifeq ($(TARGET_64BIT), 1)
``` 

```
Compiling dimuse_codecs.cpp...
during RTL pass: late_combine
In file included from /var/media/DATA/home-rudi/LibreELEC.kernel11/build.LibreELEC-H3.arm-13.0-devel/build/libretro-scummvm-7310d4e9f5d11553c6c5499911bd2f9b8ff3db3b/backends/platform/libretro/../../../engines/scumm/scumm.h:36,
                 from /var/media/DATA/home-rudi/LibreELEC.kernel11/build.LibreELEC-H3.arm-13.0-devel/build/libretro-scummvm-7310d4e9f5d11553c6c5499911bd2f9b8ff3db3b/backends/platform/libretro/../../../engines/scumm/imuse/instrument.cpp:22:
/var/media/DATA/home-rudi/LibreELEC.kernel11/build.LibreELEC-H3.arm-13.0-devel/build/libretro-scummvm-7310d4e9f5d11553c6c5499911bd2f9b8ff3db3b/backends/platform/libretro/../../../common/serializer.h: In function 'void Common::Serializer::syncAsByte(T&, Version, Version) [with T = unsigned char]':
/var/media/DATA/home-rudi/LibreELEC.kernel11/build.LibreELEC-H3.arm-13.0-devel/build/libretro-scummvm-7310d4e9f5d11553c6c5499911bd2f9b8ff3db3b/backends/platform/libretro/../../../common/serializer.h:53:9: internal compiler error: Segmentation fault
   53 |         }
      |         ^
/var/media/DATA/home-rudi/LibreELEC.kernel11/build.LibreELEC-H3.arm-13.0-devel/build/libretro-scummvm-7310d4e9f5d11553c6c5499911bd2f9b8ff3db3b/backends/platform/libretro/../../../common/serializer.h:117:9: note: in expansion of macro 'SYNC_AS'
  117 |         SYNC_AS(Byte, byte, 1)
      |         ^~~~~~~
0x1dd2c77 diagnostic_context::diagnostic_impl(rich_location*, diagnostic_metadata const*, diagnostic_option_id, char const*, __va_list_tag (*) [1], diagnostic_t)
        ???:0
0x1de3bee internal_error(char const*, ...)
        ???:0
0xf36df3 crash_signal(int)
        ???:0
0x1cf0778 rtl_ssa::clobber_info::recompute_group()
        ???:0
0x1ca6947 rtl_ssa::access_info* rtl_ssa::last_access<(anonymous namespace)::insn_combination::substitute_nondebug_use(rtl_ssa::use_info*)::local_ignore>(rtl_ssa::def_info*, rtl_ssa::ignore_clobbers, (anonymous namespace)::insn_combination::substitute_nondebug_use(rtl_ssa::use_info*)::local_ignore)
        ???:0
0x1ca7ceb (anonymous namespace)::insn_combination::substitute_nondebug_uses(rtl_ssa::set_info*)
        ???:0
0x1ca79cb (anonymous namespace)::insn_combination::substitute_nondebug_uses(rtl_ssa::set_info*)
        ???:0
0x1ca8d6e (anonymous namespace)::late_combine::combine_into_uses(rtl_ssa::insn_info*, rtl_ssa::insn_info*)
        ???:0
0x1ca95d9 (anonymous namespace)::pass_late_combine::execute(function*)
        ???:0
Please submit a full bug report, with preprocessed source (by using -freport-bug).
Please include the complete backtrace with any bug report.
See <https://gcc.gnu.org/bugs/> for instructions.
make: *** [Makefile:675: engines/scumm/imuse/instrument.o] Error 1
make: *** Waiting for unfinished jobs....
during RTL pass: late_combine
In file included from /var/media/DATA/home-rudi/LibreELEC.kernel11/build.LibreELEC-H3.arm-13.0-devel/build/libretro-scummvm-7310d4e9f5d11553c6c5499911bd2f9b8ff3db3b/backends/platform/libretro/../../../engines/scumm/sound.h:26,
                 from /var/media/DATA/home-rudi/LibreELEC.kernel11/build.LibreELEC-H3.arm-13.0-devel/build/libretro-scummvm-7310d4e9f5d11553c6c5499911bd2f9b8ff3db3b/backends/platform/libretro/../../../engines/scumm/players/player_towns.cpp:23:
/var/media/DATA/home-rudi/LibreELEC.kernel11/build.LibreELEC-H3.arm-13.0-devel/build/libretro-scummvm-7310d4e9f5d11553c6c5499911bd2f9b8ff3db3b/backends/platform/libretro/../../../common/serializer.h: In function 'void Common::Serializer::syncAsByte(T&, Version, Version) [with T = unsigned char]':
/var/media/DATA/home-rudi/LibreELEC.kernel11/build.LibreELEC-H3.arm-13.0-devel/build/libretro-scummvm-7310d4e9f5d11553c6c5499911bd2f9b8ff3db3b/backends/platform/libretro/../../../common/serializer.h:53:9: internal compiler error: Segmentation fault
   53 |         }
      |         ^
/var/media/DATA/home-rudi/LibreELEC.kernel11/build.LibreELEC-H3.arm-13.0-devel/build/libretro-scummvm-7310d4e9f5d11553c6c5499911bd2f9b8ff3db3b/backends/platform/libretro/../../../common/serializer.h:117:9: note: in expansion of macro 'SYNC_AS'
  117 |         SYNC_AS(Byte, byte, 1)
      |         ^~~~~~~
0x1dd2c77 diagnostic_context::diagnostic_impl(rich_location*, diagnostic_metadata const*, diagnostic_option_id, char const*, __va_list_tag (*) [1], diagnostic_t)
        ???:0
0x1de3bee internal_error(char const*, ...)
        ???:0
0xf36df3 crash_signal(int)
        ???:0
0x1cf0778 rtl_ssa::clobber_info::recompute_group()
        ???:0
0x1ca6947 rtl_ssa::access_info* rtl_ssa::last_access<(anonymous namespace)::insn_combination::substitute_nondebug_use(rtl_ssa::use_info*)::local_ignore>(rtl_ssa::def_info*, rtl_ssa::ignore_clobbers, (anonymous namespace)::insn_combination::substitute_nondebug_use(rtl_ssa::use_info*)::local_ignore)
        ???:0
0x1ca7ceb (anonymous namespace)::insn_combination::substitute_nondebug_uses(rtl_ssa::set_info*)
        ???:0
0x1ca79cb (anonymous namespace)::insn_combination::substitute_nondebug_uses(rtl_ssa::set_info*)
        ???:0
0x1ca8d6e (anonymous namespace)::late_combine::combine_into_uses(rtl_ssa::insn_info*, rtl_ssa::insn_info*)
        ???:0
0x1ca95d9 (anonymous namespace)::pass_late_combine::execute(function*)
        ???:0
Please submit a full bug report, with preprocessed source (by using -freport-bug).
Please include the complete backtrace with any bug report.
See <https://gcc.gnu.org/bugs/> for instructions.
make: *** [Makefile:675: engines/scumm/players/player_towns.o] Error 1
```

**Comment by spleen1981** [comment]
fixed by e566a6432fd1951417bf78280cc7c741957fc419

**Comment by heitbaum** [comment]
> fixed by [e566a64](https://github.com/libretro/scummvm/commit/e566a6432fd1951417bf78280cc7c741957fc419)

Hi @spleen1981 - I got round to checking CI/CD and it was still failing. I have had to reverse the lookup as findstring was not finding platform in armv7.

```
Executing (target): make all platform=armv7a-libreelec-linux-gnueabihf
Platform is armv7a-libreelec-linux-gnueabihf 32bit
```
fix should be
```diff
diff --git a/packages/emulation/libretro-scummvm/patches/0003-libretro-fix-armv7-GCC-15.1-internal-compiler-error.patch b/packages/emulation/libretro-scummvm/patches/0003-libretr
o-fix-armv7-GCC-15.1-internal-compiler-error.patch
index 29728dfcb3..360ca9d8d6 100644
--- a/packages/emulation/libretro-scummvm/patches/0003-libretro-fix-armv7-GCC-15.1-internal-compiler-error.patch
+++ b/packages/emulation/libretro-scummvm/patches/0003-libretro-fix-armv7-GCC-15.1-internal-compiler-error.patch
@@ -15,7 +15,7 @@ index 0181825bfbbc..383a25cab706 100644
     DEFINES += -Os
  else ifneq (,$(findstring $(platform), ios osx))
     DEFINES += -O1
-+else ifneq (,$(findstring $(platform), armv7)) # fixes a GCC 15.1 internal compiler error. TODO check if it is fixed in GCC newer releases.
++else ifneq (,$(findstring armv7, $(platform))) # fixes a GCC 15.1 internal compiler error. TODO check if it is fixed in GCC newer releases.
 +   DEFINES += -O1
  else ifneq (,$(findstring $(platform), msvc genode rpi))
     DEFINES += -O2
```

**Comment by spleen1981** [comment]
agreed, fixed by f1b1e7cf73c5d0be804275ec4baba82262246c13
